version: '3'

services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: Password123
    ports:
      - "5432:5432"

  web:
    build: .
    command: /wait_for_db.sh db:5432 -- python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
        - "8000:8000"
    depends_on:
        - db
    environment:
        - DATABASE_URL=postgres://geo_user:Password123@db:5432/geodb